{% set version = "2023.9.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-inlinedocs
  version: {{ version|replace("-", "_") }}

source:
  fn: inlinedocs_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/inlinedocs_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/inlinedocs/inlinedocs_{{ version }}.tar.gz
  sha256: 635a0e2619028ac5b07e11ea8c807dd7f9743e6eb52085ab584cc9eaccb3b584

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('inlinedocs')"  # [not win]
    - "\"%R%\" -e \"library('inlinedocs')\""  # [win]

about:
  home: http://inlinedocs.r-forge.r-project.org
  license: GPL-2 | GPL-3
  summary: Generates Rd files from R source code with comments. The main features of the default syntax are that (1) docs are defined in comments near the relevant code, (2) function argument names are not repeated in comments, and (3) examples are defined in R code, not comments. It is also easy to define a new syntax.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
