appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: l5T3RNQ5WYH968uorP8PBEaAev0EoQk9NaKjDPIbZOdtdITWps243azubHP3EfCoufyNNbgF32pa1dHsCcZ+WiYOsiyiHjCaZ7a6xtWi891hezTJuYAtrKJu9tm14Hk4QpH4nP882h9OE++giaBczrdBcnK5eVPuot1gcywiwJPY/tLjCh9nMEazbHEoJ6x7vSz7/WCIgHiOj6W5cfKxKdAfmzBRyOITzYq+vHqz9gB8Ah2LPVz/ZmGqTedai0U5wt7IH/1FrQev2EFHo1uLZ3c3VDtr6u7xGEi3gNZrVdvnGqlAQBbe5Phvn28rgxIgzKcnm/Qf7Jg9fP0iGvHGxhxZ6wGnSPc1Ab9kehRT0jO76HFoiszd3gbIR9lJx8eDfR2FSXHeHelvS+XJBCrjZTZZJzT9C01uY/MAMWa729NJaR4/w6eaAzZqBbyJShizdT7j+bB7te8Q823u+BBLlnK30nqearJCRAL4T1vtjmQW/zl3PShWtAbQWwwTvp/ZErpd2cBGFXdClXw3Xd/ilao4KHHEtmWoW/7eXO1zKjfIuMxL0Ay1+sPPZnYJtXuSTERNQizkKCMWOzvmdBCxQWY1F123drySUtYy7o62ffxy17KLa5Zg25CVibZ23Tt5IGv0BAhaLBAIOD1hL1QSOJBOxQqvO1UlYtbt6fyKFD4=}
